#!/bin/sh
set -e

FILE=$1

head -`fgrep -n END_SAMPLE ${FILE:?}.hp | tail -1 | cut -d : -f 1` ${FILE:?}.hp \
  | hp2ps -c > ${FILE:?}.ps

gv -orientation=seascape ${FILE:?}.ps &
gvpsnum=$!

while [ 1 ] ; do
  sleep 5
  head -`fgrep -n END_SAMPLE ${FILE:?}.hp | tail -1 | cut -d : -f 1` ${FILE:?}.hp \
    | hp2ps -c > ${FILE:?}.ps
  kill -HUP $gvpsnum
done
